type Collection = {
  name: string
  address: string
  description: string
  image: string
  banner: any[]
  rules: string[]
}
export const collections: { [key: string]: { [key: string]: Collection } } = {
  mainnet: {
    'the-random-collection': {
      address: 'TQNUyaZxpkYHUtk31LGXHtduanGrYnVau6',
      name: 'The Random Collection',
      description:
        'A collection of random images, generated by Stable Diffusion and DALL-E 2. Go to https://xpromptnft.xyz to generate your own!',
      image:
        'https://aigenerated.infura-ipfs.io/ipfs/QmXJFer9tFZAn4qEccyQCjUaw9pZXmfaJhbRsZ6Avn9XnZ',
      banner: [
        {
          nft: 'https://apenft.io/assets/TQNUyaZxpkYHUtk31LGXHtduanGrYnVau6/1',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmXJFer9tFZAn4qEccyQCjUaw9pZXmfaJhbRsZ6Avn9XnZ',
        },
        {
          nft: 'https://testnetpenft.io/assets/TQNUyaZxpkYHUtk31LGXHtduanGrYnVau6/2',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmfPdJZdJHHeACBPi5JK6p12yFb3uoAfgj1b1AJeMr3xUm',
        },
        {
          nft: 'https://apenft.io/assets/TQNUyaZxpkYHUtk31LGXHtduanGrYnVau6/3',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmTGLrEabuXbAxUYu4gwJrhiS5y8Jo1A92XdyCJ7bnPj5q',
        },
        {
          nft: 'https://apenft.io/assets/TQNUyaZxpkYHUtk31LGXHtduanGrYnVau6/4',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmdGbhQeryn6bmUiMv2mzgttJZ1vk2KNWUtd6gdNthKuE6',
        },
        {
          nft: 'https://apenft.io/assets/TQNUyaZxpkYHUtk31LGXHtduanGrYnVau6/5',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmRrViECVyvApHjojrPB8yf7megn5FkVEnmwACK54sMNsX',
        },
        {
          nft: 'https://apenft.io/assets/TQNUyaZxpkYHUtk31LGXHtduanGrYnVau6/6',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmcqhDwYuq27cX9xp3weDbPLVkKEdmSgTxCThUM5e3Y3bJ',
        },
        {
          nft: 'https://apenft.io/assets/TQNUyaZxpkYHUtk31LGXHtduanGrYnVau6/7',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmQNF6FhjkGCn5SN31B9Enevfe5rBzRm7SRqEuH4KCekgK',
        },
      ],
      rules: [],
    },
    'the-dog-collection': {
      address: 'TN7m8KP5vWUtGKMZW6LF7WkbodojMz3bJ7',
      name: 'The Dog Collection',
      description:
        'A collection of dog related images, generated by Stable Diffusion and DALL-E 2. Go to https://xpromptnft.xyz to generate your own!',
      image:
        'https://aigenerated.infura-ipfs.io/ipfs/QmcS2CWjt7LDmKYme9dhiSWX9kBC19yYw5MMuRGufesjNA',
      banner: [
        {
          nft: 'https://apenft.io/assets/TN7m8KP5vWUtGKMZW6LF7WkbodojMz3bJ7/1',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmQH3dg2A88XVgGZfkSK7YYf5eLSQtNAH3217Npx3j3x6m',
        },
        {
          nft: 'https://apenft.io/assets/TN7m8KP5vWUtGKMZW6LF7WkbodojMz3bJ7/2',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmcS2CWjt7LDmKYme9dhiSWX9kBC19yYw5MMuRGufesjNA',
        },
        {
          nft: 'https://apenft.io/assets/TN7m8KP5vWUtGKMZW6LF7WkbodojMz3bJ7/3',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmbUk467x7x3PzCkJTAbW6P9JK2pSkbrbwsfNTWZNYzFW6',
        },
        {
          nft: 'https://apenft.io/assets/TN7m8KP5vWUtGKMZW6LF7WkbodojMz3bJ7/4',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmXkaz7B1rqLKndNE6xRPVoSZhBJyp854UEW9Vtg12iFJ7',
        },
        {
          nft: 'https://apenft.io/assets/TN7m8KP5vWUtGKMZW6LF7WkbodojMz3bJ7/5',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmUCYK8aZeYoeyrAyVn8gJCKLdqN1e6bFwQuAGnueetewA',
        },
        {
          nft: 'https://apenft.io/assets/TN7m8KP5vWUtGKMZW6LF7WkbodojMz3bJ7/6',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmV4A9ZnYkLXEN4NhdMasgNz5fH872vEXw1cokWyyePWac',
        },
        {
          nft: 'https://apenft.io/assets/TN7m8KP5vWUtGKMZW6LF7WkbodojMz3bJ7/7',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmbvR1JYSzcgjuFpJcZhfvWHnzpGbizp7cdUgBTtHWuhrH',
        },
      ],
      rules: [
        'dog',
        'shiba',
        'corgi',
        'cavapoo',
        'labradoodle',
        'golden retriever',
        'pitbull dog',
        'bulldog',
        'poodle',
        'rottweiler',
        'german shepherd',
        'terrier',
        'cavalier king charles spaniel',
        'doberman',
        'schnauzer',
        'siberian husky',
        'havanese',
        'cockapoo',
        'cocker spaniel',
        'pug',
        'mastiff',
        'labrador',
        'samoyed',
      ],
    },
    'the-space-collection': {
      address: 'TYUw4YEgap1rAeQYPmVmDdD9kEkp8jqnBh',
      name: 'The Space Collection',
      description:
        'A collection of space related images, generated by Stable Diffusion and DALL-E 2. Go to https://xpromptnft.xyz to generate your own!',

      image:
        'https://aigenerated.infura-ipfs.io/ipfs/QmW96eG8nHZCCKzzCUHGWubGD6Qojve6xnkcEVYZc2nVRR',
      banner: [
        {
          nft: 'https://apenft.io/assets/TYUw4YEgap1rAeQYPmVmDdD9kEkp8jqnBh/1',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmRYzLvqV4phhRCb1pPStsW7z5AsKpk94KtcJyTmjFnzGU',
        },
        {
          nft: 'https://apenft.io/assets/TYUw4YEgap1rAeQYPmVmDdD9kEkp8jqnBh/2',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmXDFAPbXqGwbTnopvZPhENBDU1YqgmeWe1FoXDJuuxcNX',
        },
        {
          nft: 'https://apenft.io/assets/TYUw4YEgap1rAeQYPmVmDdD9kEkp8jqnBh/3',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmQCicrcmSCu424scYqmBUgRATS2UbUK6sWDAtgBhJaFLt',
        },
        {
          nft: 'https://apenft.io/assets/TYUw4YEgap1rAeQYPmVmDdD9kEkp8jqnBh/4',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmY69Nd6XqStuN62yLGjkC7k6DVeFyVoZydRskXfuVRoxc',
        },
        {
          nft: 'https://apenft.io/assets/TYUw4YEgap1rAeQYPmVmDdD9kEkp8jqnBh/5',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/Qma5FqVKLZ7iaEufDKZhPoAW4wGvwid5zGPU6Rt1TUso5Q',
        },
        {
          nft: 'https://apenft.io/assets/TYUw4YEgap1rAeQYPmVmDdD9kEkp8jqnBh/6',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/Qme7i4q3xW2CVVfFKVwfBkVomZbGxAEYsn7tzCzi9WaF25',
        },
        {
          nft: 'https://apenft.io/assets/TYUw4YEgap1rAeQYPmVmDdD9kEkp8jqnBh/7',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmaXTHSGih8a9NamaKhJMzSTGUdiroVJXLxpoMfJoNEuTc',
        },
      ],
      rules: [
        'space',
        'universe',
        'black hole',
        'wormhole',
        'supernova',
        'extraterrestial',
        'astronaut',
        'galaxy',
        'galaxies',
        'stars',
        'milky way',
        'nebula',
        'planet',
        'mercury',
        'venus',
        'tellus',
        'moon',
        'mars',
        'jupiter',
        'saturn',
        'uranus',
        'neptune',
        'pluto',
      ],
    },
    'the-walter-white-collection': {
      address: 'TXV5K3WQ6azqLy5JW8tc7fUEbK6dxEt7A2',
      name: 'The Walter White Collection',
      description:
        'A collection of Walter White related images, generated by Stable Diffusion and DALL-E 2. Go to https://xpromptnft.xyz to generate your own!',
      banner: [
        {
          nft: 'https://apenft.io/assets/TXV5K3WQ6azqLy5JW8tc7fUEbK6dxEt7A2/1',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmXXLGzeRe9CdQkMV9ptndW27U55gCSCdM1kmJeuh6Az3P',
        },
        {
          nft: 'https://apenft.io/assets/TXV5K3WQ6azqLy5JW8tc7fUEbK6dxEt7A2/2',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmcFLkZWHKhgtEEVPMhMZLbQKTuf45imvyedTN5LQ2DzsT',
        },
        {
          nft: 'https://apenft.io/assets/TXV5K3WQ6azqLy5JW8tc7fUEbK6dxEt7A2/3',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmbJ4qogJXUQDRc3GMUF9uJCStkmpBTz8923uqDVjEi4v8',
        },
        {
          nft: 'https://apenft.io/assets/TXV5K3WQ6azqLy5JW8tc7fUEbK6dxEt7A2/4',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmWkrb2xSL6P7YdUYkxsFbgnDRRAA6huFTCXinNUb65q47',
        },
        {
          nft: 'https://apenft.io/assets/TXV5K3WQ6azqLy5JW8tc7fUEbK6dxEt7A2/5',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmTdwTpiM14NThwZKvQG2Ph5qVXDxNvXiEHxjYMt8fU66S',
        },
        {
          nft: 'https://apenft.io/assets/TXV5K3WQ6azqLy5JW8tc7fUEbK6dxEt7A2/6',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmSmG2TuQQ2x35zZkx315oZgHPdEFbPQjmAoNDSGH9Y1Cd',
        },
        {
          nft: 'https://apenft.io/assets/TXV5K3WQ6azqLy5JW8tc7fUEbK6dxEt7A2/7',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmQ5CtfVwewpgzLKQza6BaTkN3yw1pfk5H2kGqTLURXKtQ',
        },
      ],
      image:
        'https://aigenerated.infura-ipfs.io/ipfs/QmXXLGzeRe9CdQkMV9ptndW27U55gCSCdM1kmJeuh6Az3P',
      rules: ['walter white', 'bryan cranston', 'heisenberg'],
    },
  },
  shasta: {
    'the-random-collection': {
      address: 'TNZSa7zDpKEQDHsrDGxshnjYpiVfjMMhhB',
      name: 'The Random Collection',
      description:
        'A collection of random images, generated by Stable Diffusion and DALL-E 2. Go to https://xpromptnft.xyz to generate your own!',
      image:
        'https://aigenerated.infura-ipfs.io/ipfs/QmXJFer9tFZAn4qEccyQCjUaw9pZXmfaJhbRsZ6Avn9XnZ',
      banner: [
        {
          nft: 'https://testnet.apenft.io/assets/TNZSa7zDpKEQDHsrDGxshnjYpiVfjMMhhB/1',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmXJFer9tFZAn4qEccyQCjUaw9pZXmfaJhbRsZ6Avn9XnZ',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TNZSa7zDpKEQDHsrDGxshnjYpiVfjMMhhB/2',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmfPdJZdJHHeACBPi5JK6p12yFb3uoAfgj1b1AJeMr3xUm',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TNZSa7zDpKEQDHsrDGxshnjYpiVfjMMhhB/3',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmTGLrEabuXbAxUYu4gwJrhiS5y8Jo1A92XdyCJ7bnPj5q',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TNZSa7zDpKEQDHsrDGxshnjYpiVfjMMhhB/4',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmdGbhQeryn6bmUiMv2mzgttJZ1vk2KNWUtd6gdNthKuE6',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TNZSa7zDpKEQDHsrDGxshnjYpiVfjMMhhB/5',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmRrViECVyvApHjojrPB8yf7megn5FkVEnmwACK54sMNsX',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TNZSa7zDpKEQDHsrDGxshnjYpiVfjMMhhB/6',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmcqhDwYuq27cX9xp3weDbPLVkKEdmSgTxCThUM5e3Y3bJ',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TNZSa7zDpKEQDHsrDGxshnjYpiVfjMMhhB/7',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmQNF6FhjkGCn5SN31B9Enevfe5rBzRm7SRqEuH4KCekgK',
        },
      ],
      rules: [],
    },
    'the-dog-collection': {
      address: 'TFJyRxGwabFtAktRi3aZAREpqdWZKUcAqi',
      name: 'The Dog Collection',
      description:
        'A collection of dog related images, generated by Stable Diffusion and DALL-E 2. Go to https://xpromptnft.xyz to generate your own!',
      image:
        'https://aigenerated.infura-ipfs.io/ipfs/QmcS2CWjt7LDmKYme9dhiSWX9kBC19yYw5MMuRGufesjNA',
      banner: [
        {
          nft: 'https://testnet.apenft.io/assets/TFJyRxGwabFtAktRi3aZAREpqdWZKUcAqi/3',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmQH3dg2A88XVgGZfkSK7YYf5eLSQtNAH3217Npx3j3x6m',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TFJyRxGwabFtAktRi3aZAREpqdWZKUcAqi/5',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmcS2CWjt7LDmKYme9dhiSWX9kBC19yYw5MMuRGufesjNA',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TFJyRxGwabFtAktRi3aZAREpqdWZKUcAqi/7',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmbUk467x7x3PzCkJTAbW6P9JK2pSkbrbwsfNTWZNYzFW6',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TFJyRxGwabFtAktRi3aZAREpqdWZKUcAqi/9',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmXkaz7B1rqLKndNE6xRPVoSZhBJyp854UEW9Vtg12iFJ7',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TFJyRxGwabFtAktRi3aZAREpqdWZKUcAqi/8',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmUCYK8aZeYoeyrAyVn8gJCKLdqN1e6bFwQuAGnueetewA',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TFJyRxGwabFtAktRi3aZAREpqdWZKUcAqi/4',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmV4A9ZnYkLXEN4NhdMasgNz5fH872vEXw1cokWyyePWac',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TFJyRxGwabFtAktRi3aZAREpqdWZKUcAqi/6',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmbvR1JYSzcgjuFpJcZhfvWHnzpGbizp7cdUgBTtHWuhrH',
        },
      ],
      rules: [
        'dog',
        'shiba',
        'corgi',
        'cavapoo',
        'labradoodle',
        'golden retriever',
        'pitbull dog',
        'bulldog',
        'poodle',
        'rottweiler',
        'german shepherd',
        'terrier',
        'cavalier king charles spaniel',
        'doberman',
        'schnauzer',
        'siberian husky',
        'havanese',
        'cockapoo',
        'cocker spaniel',
        'pug',
        'mastiff',
        'labrador',
        'samoyed',
      ],
    },
    'the-space-collection': {
      address: 'TB83uWMKNRf8iUepVR8bjDewX19He2tDMf',
      name: 'The Space Collection',
      description:
        'A collection of space related images, generated by Stable Diffusion and DALL-E 2. Go to https://xpromptnft.xyz to generate your own!',
      image:
        'https://aigenerated.infura-ipfs.io/ipfs/QmW96eG8nHZCCKzzCUHGWubGD6Qojve6xnkcEVYZc2nVRR',
      banner: [
        {
          nft: 'https://testnet.apenft.io/assets/TB83uWMKNRf8iUepVR8bjDewX19He2tDMf/1',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmRfymvWNverAcHBrNeNcGeCMujzvsNgMsdFwjK4zhU73w',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TB83uWMKNRf8iUepVR8bjDewX19He2tDMf/3',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmYTz24fB2fXgQENCviD9N1WqJvH6kVU7tjfz62dbJoxpq',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TB83uWMKNRf8iUepVR8bjDewX19He2tDMf/5',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmakwJL5kB37Rs6mQc8xDqPhcerYL12qVdMLVkh5zz7iMs',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TB83uWMKNRf8iUepVR8bjDewX19He2tDMf/8',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmVAH1Zh1ymKULCSei1uTiJhRZG8NSqXxzYTs3ELHqCpJj',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TB83uWMKNRf8iUepVR8bjDewX19He2tDMf/10',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmW96eG8nHZCCKzzCUHGWubGD6Qojve6xnkcEVYZc2nVRR',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TB83uWMKNRf8iUepVR8bjDewX19He2tDMf/9',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmVNrc9WQBh6oDnXbQ1cKj7bG2T3admhbafmXGA49z7nKT',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TB83uWMKNRf8iUepVR8bjDewX19He2tDMf/11',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmYVPCUF9enNeucMubthL1PfQw2SbziQKkKXm6QwhVXdzQ',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TB83uWMKNRf8iUepVR8bjDewX19He2tDMf/12',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmP7A34HzE2PQZ8Xrmcfd1vuexJ6k8vkrX9vsiZ5Sx8YGk',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TB83uWMKNRf8iUepVR8bjDewX19He2tDMf/13',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/Qma5Ru93tZfHJndRks927dQDWQgFLUjVHnCBjVYd55Cd7Y',
        },
      ],
      rules: [
        'space',
        'universe',
        'black hole',
        'wormhole',
        'supernova',
        'extraterrestial',
        'astronaut',
        'galaxy',
        'galaxies',
        'stars',
        'milky way',
        'nebula',
        'planet',
        'mercury',
        'venus',
        'tellus',
        'moon',
        'mars',
        'jupiter',
        'saturn',
        'uranus',
        'neptune',
        'pluto',
      ],
    },
    'the-walter-white-collection': {
      address: 'TJmH96j2z9Zs6Eto1aU1xtsbdSHgXCJ4b5',
      name: 'The Walter White Collection',
      description:
        'A collection of Walter White related images, generated by Stable Diffusion and DALL-E 2. Go to https://xpromptnft.xyz to generate your own!',
      banner: [
        {
          nft: 'https://testnet.apenft.io/assets/TJmH96j2z9Zs6Eto1aU1xtsbdSHgXCJ4b5/1',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmXXLGzeRe9CdQkMV9ptndW27U55gCSCdM1kmJeuh6Az3P',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TJmH96j2z9Zs6Eto1aU1xtsbdSHgXCJ4b5/2',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmcFLkZWHKhgtEEVPMhMZLbQKTuf45imvyedTN5LQ2DzsT',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TJmH96j2z9Zs6Eto1aU1xtsbdSHgXCJ4b5/3',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmbJ4qogJXUQDRc3GMUF9uJCStkmpBTz8923uqDVjEi4v8',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TJmH96j2z9Zs6Eto1aU1xtsbdSHgXCJ4b5/4',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmWkrb2xSL6P7YdUYkxsFbgnDRRAA6huFTCXinNUb65q47',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TJmH96j2z9Zs6Eto1aU1xtsbdSHgXCJ4b5/5',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmTdwTpiM14NThwZKvQG2Ph5qVXDxNvXiEHxjYMt8fU66S',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TJmH96j2z9Zs6Eto1aU1xtsbdSHgXCJ4b5/6',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmSmG2TuQQ2x35zZkx315oZgHPdEFbPQjmAoNDSGH9Y1Cd',
        },
        {
          nft: 'https://testnet.apenft.io/assets/TJmH96j2z9Zs6Eto1aU1xtsbdSHgXCJ4b5/7',
          image:
            'https://aigenerated.infura-ipfs.io/ipfs/QmQ5CtfVwewpgzLKQza6BaTkN3yw1pfk5H2kGqTLURXKtQ',
        },
      ],
      image:
        'https://aigenerated.infura-ipfs.io/ipfs/QmXXLGzeRe9CdQkMV9ptndW27U55gCSCdM1kmJeuh6Az3P',
      rules: ['walter white', 'bryan cranston', 'heisenberg'],
    },
  },
}
